### ISSUE TITLE
Review tracker

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnx-script#498]
@justinchuby is using this issue to track review items.

- [x] https://github.com/microsoft/onnx-script/pull/314/files#diff-e94a882bd9dcdfc75120b0571c970a28d35ec65bf9b8ba02b68a8b442f2853a7R3294 Ways to create overloads. Include ATen signatures.
- [x] https://github.com/microsoft/onnx-script/pull/483 Correctness test
- [x] https://github.com/microsoft/onnx-script/pull/444/files#r1125504175 Comments
- [x] https://github.com/microsoft/onnx-script/pull/490/files#r1126647132 
- [x] https://github.com/microsoft/onnx-script/pull/490/files#r1126659450
- [x] https://github.com/microsoft/onnx-script/pull/463#discussion_r1125417498
- [x] https://github.com/microsoft/onnx-script/pull/463/files#r1126701529
